### ISSUE TITLE
how to install tensorflow lite (Raspberry Pi)

### ISSUE THREAD

**Issue by wzhsysu** [huaxiaozhong1/tensorflow-lite-apps-on-raspberry-pi-3#2]
您好，我在完成编译之后生成两个.a文件，之后就不知道怎么使用这两个文件了。
https://www.tensorflow.org/lite/guide/build_rpi
您这个是怎么使用的呢？

Best

**Comment by huaxiaozhong1** [comment]
Hello, what 2 .a files did you get from your compilation? My project was based tensorflow 1.12. So, I guess that you talked about on running:
tensorflow/tensorflow/contrib/lite/tools/make/build_rpi_lib.sh. After running it, tensorflow/tensorflow/contrib/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a was created. Is that the .a file that you mentioned?
Thanks,

**Comment by wzhsysu** [comment]
Yes, it is really what you said. After the creation of two .a files, I do not know how to use it, how to run the demo? can you provide some more details for us?

Thanks

**Comment by huaxiaozhong1** [comment]
Could you let me know the names for the 2 .a files?

**Comment by huaxiaozhong1** [comment]
According to my description at the github project, you should, at the docker container, get 2 executable apps: label_image and camera. Copy the 2 apps to your device (that is nano pi, at your case), the expectation is that the 2 apps could run over there.

**Comment by huaxiaozhong1** [comment]
As for benchmark-lib.a and libtensorflow-lite.a, the .a files you got, could you check tensorflow/tensorflow/contrib/lite/tools/make/Makefile? That is where the .a files are used.
tensorflow/tensorflow/contrib/lite/tools/make/build_rpi_lib.sh will link them to create the 2 apps. It was done in docker container in host, on my case.
Using docker container could guarantee a clear environment for cross-compilation, which generates, at host, the apps that will run at device.

**Comment by huaxiaozhong1** [comment]
Regarding to raspberry PI, no need to install tensoflow lite on it. The app, such as camera, includes libtensorflow-lite.a, which has all tensorflow lite inside.

**Comment by huaxiaozhong1** [comment]
Hi, if you don't have the further questions, could you close the issue? Best,
